id: IC2DFF9D4
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T14:53:54.142681'
last_modified: '2022-05-27T14:53:54.142694'
parser: null
source_metadata:
  title: Dīrghāgama, sūtras no. 35-41
  language: sa
  base:
    f674F:
      title: Complete text
      base_file: f674F.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
